### ISSUE TITLE
Unable to use Gearman ui

### ISSUE THREAD

**Issue by nikhildhawan** [gaspaio/gearmanui#1]
so i tried to use gearman-ui for viewing server status but the index page in web is always giving me error 

```
Job queue
Workers
Servers' status
```

{{ error }} 

I tried to change config to make log for debug level (100) and only thing i got in logs inside app/logs is 
18 10:37:24] GearmanUI.INFO: Matched route "GET_" (parameters: "_controller": "{}", "_route": "GET_") [] []
[2013-04-18 10:37:24] GearmanUI.INFO: > GET /gearman-ui/web/ [] []
[2013-04-18 10:37:24] GearmanUI.INFO: < 200 [] []
[2013-04-18 10:37:28] GearmanUI.INFO: Matched route "GET_" (parameters: "_controller": "{}", "_route": "GET_") [] []
[2013-04-18 10:37:28] GearmanUI.INFO: > GET /gearman-ui/web/ [] []
[2013-04-18 10:37:29] GearmanUI.INFO: < 200 [] []

Can you please help me find out what is missing.

**Comment by webbpinner** [comment]
after following all the recommendations here I was still unable to get my gearman-ui site working with mod_rewrite.  Ultimately I did get mod_rewrite working for my gearman-ui installation by adding the following line to the .htaccess file: RewriteBase /gearman-ui

My .htaccess file now looks like this:
<IfModule mod_rewrite.c>
    Options -MultiViews

    RewriteEngine On
    RewriteBase /gearman-ui
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^ index.php [L]
</IfModule>

Cheers,
-W
