### ISSUE TITLE
Server Error while accessing URL '/info': 404 - Not Found

### ISSUE THREAD

**Issue by fanphp** [gaspaio/gearmanui#16]
Hi,
I'm getting this error:

Server Error while accessing URL '/info': 404 - Not Found

can you help me?

thanks

**Comment by fanphp** [comment]
Solved: It was an apache issue. Thanks.

**Comment by bilua-xiaolei** [comment]
In case somebody arrives to this post, you have to enable "mod_rewrite":

sudo a2enmod rewrite
